services:
  my-app:
    image: 46.101.99.188:8083/my-app:1.0
    ports:
      - 3000:3000
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 5000:5000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock://var/run/docker.sock
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"
volumes:
  mongo-data:
    driver: local
  jenkins_home:
    driver: local
